### POST

POST http://127.0.0.1:8080/analyze
Content-Type: application/json

{
  "url": "https://www.laprensani.com/2025/12/14/nacionales/3575501-ex-reos-politicos-culminan-maestria-en-ee-uu-y-resaltan-el-aporte-del-exilio-al-futuro-de-nicaragua"
}

# Obtener primera página (10 items por defecto)
### GET

GET http://127.0.0.1:8080/history
Content-Type: application/json

### GET
GET http://localhost:8080/history?page=2
Content-Type: application/json

### GET
GET http://localhost:8080/history?page=1&page_size=20
Content-Type: application/json

## POST GET Favoritos
### GET
GET http://localhost:8080/favorites?page=1&page_size=10
Content-Type: application/json

### POST
POST http://localhost:8080/favorites
Content-Type: application/json

{
  "analysis_id": 1
}

### DELETE
DELETE http://localhost:8080/favorites/1
Content-Type: application/json