package_rename_config:
  android:
    app_name: DaktarLamaraApp
    package_name: dev.donmanuel.daktarlamara
    override_old_package: com.example.healthpal

  ios:
    app_name: DaktarLamaraApp
    bundle_name: DaktarLamaraApp
    package_name: dev.donmanuel.daktarlamara

